services:
  - type: worker
    name: innokentiy-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python innokentiy_bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DEEPINFRA_API_KEY
        sync: false
